[2024-12-30T20:55:43.383+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:55:43.410+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_weather.fetch_and_publish_weather manual__2024-12-30T20:55:41.505055+00:00 [queued]>
[2024-12-30T20:55:43.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_weather.fetch_and_publish_weather manual__2024-12-30T20:55:41.505055+00:00 [queued]>
[2024-12-30T20:55:43.427+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:55:43.450+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:55:41.505055+00:00
[2024-12-30T20:55:43.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=265) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:55:43.462+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_weather', 'fetch_and_publish_weather', 'manual__2024-12-30T20:55:41.505055+00:00', '--job-id', '758', '--raw', '--subdir', 'DAGS_FOLDER/test_weather.py', '--cfg-path', '/tmp/tmp6u2_750r']
[2024-12-30T20:55:43.463+0000] {standard_task_runner.py:72} INFO - Started process 267 to run task
[2024-12-30T20:55:43.464+0000] {standard_task_runner.py:105} INFO - Job 758: Subtask fetch_and_publish_weather
[2024-12-30T20:55:43.520+0000] {task_command.py:467} INFO - Running <TaskInstance: test_weather.fetch_and_publish_weather manual__2024-12-30T20:55:41.505055+00:00 [running]> on host 865c783184f2
[2024-12-30T20:55:43.608+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_weather' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:55:41.505055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T20:55:41.505055+00:00'
[2024-12-30T20:55:43.609+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:56:43.775+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:56:43.776+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:56:43.789+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:56:43.789+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_weather, task_id=fetch_and_publish_weather, run_id=manual__2024-12-30T20:55:41.505055+00:00, execution_date=20241230T205541, start_date=20241230T205543, end_date=20241230T205643
[2024-12-30T20:56:43.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:56:43.845+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:56:43.847+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
