[2024-12-30T20:10:06.470+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:10:06.483+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:10:00+00:00 [queued]>
[2024-12-30T20:10:06.489+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:10:00+00:00 [queued]>
[2024-12-30T20:10:06.490+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:10:06.500+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:10:00+00:00
[2024-12-30T20:10:06.507+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:10:06.509+0000] {standard_task_runner.py:72} INFO - Started process 1294 to run task
[2024-12-30T20:10:06.509+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'scheduled__2024-12-30T20:10:00+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmp2j3r8t7i']
[2024-12-30T20:10:06.510+0000] {standard_task_runner.py:105} INFO - Job 237: Subtask fetch_and_publish_weather
[2024-12-30T20:10:06.548+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:10:00+00:00 [running]> on host f4979116b9f3
[2024-12-30T20:10:06.612+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T20:10:00+00:00'
[2024-12-30T20:10:06.614+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:10:06.725+0000] {logging_mixin.py:190} INFO - Error fetching data from API for city ID 2: 404 Client Error: Not Found for url: http://api.openweathermap.org/data/2.5/forecast?id=2&lang=fr&appid=e181f39c92f75588ac5e6cb725896788&units=metric
[2024-12-30T20:10:06.726+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:10:06.734+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:10:06.735+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=scheduled__2024-12-30T20:10:00+00:00, execution_date=20241230T201000, start_date=20241230T201006, end_date=20241230T201006
[2024-12-30T20:10:06.765+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:10:06.779+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:10:06.781+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
